#!/usr/bin/env python3
"""
Model manager TUI: browse the model_catalog.json produced by
build_model_catalog.py as a scrollable list with a detail drilldown,
plus total and per-model disk usage.

Read-only view over the existing catalog -- run build_model_catalog.py
first (or after adding/removing models) to refresh results/model_catalog.json.

Usage:
    python3 scripts/model_manager.py [--catalog PATH]

Keys:
    up/down, j/k   move selection
    enter / l      drilldown into selected model
    esc / h / q    back out of drilldown, or quit from the list
    s              cycle sort (size desc -> size asc -> name -> format)
    /              filter by substring (name/path), esc clears
"""
import argparse
import curses
import json
import os
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_CATALOG = os.path.join(SCRIPT_DIR, "results", "model_catalog.json")

# Matches the multi-part suffix llama.cpp/quantizers append to split GGUFs,
# e.g. "...-Q4_K_M-00002-of-00003.gguf" -> shard 2 of 3.
SHARD_RE = re.compile(r"-(\d{5})-of-(\d{5})$")
GGUF_REPO_SUFFIX_RE = re.compile(r"[-_ ]?gguf$", re.IGNORECASE)


def human_size(num_bytes):
    for unit in ["B", "KB", "MB", "GB", "TB"]:
        if num_bytes < 1024:
            return f"{num_bytes:.1f}{unit}"
        num_bytes /= 1024
    return f"{num_bytes:.1f}PB"


def parse_gguf_filename(rel_path):
    """Derive a friendly repo/quant name and a shard-group key from a GGUF
    path, since the embedded general.name header field is frequently junk
    (auto-generated by whatever tool produced the quant, e.g. "Abl 27b") or
    simply absent on non-first shards -- the directory + filename convention
    used by GGUF repos is far more reliable."""
    dirname = os.path.dirname(rel_path)
    filename = os.path.basename(rel_path)
    stem = filename[:-5] if filename.lower().endswith(".gguf") else filename

    shard_match = SHARD_RE.search(stem)
    shard_num = shard_total = None
    group_stem = stem
    if shard_match:
        shard_num = int(shard_match.group(1))
        shard_total = int(shard_match.group(2))
        group_stem = stem[: shard_match.start()]

    # Some quant variants sit in a subdirectory under the repo (e.g.
    # ".../Laguna-S-2.1-GGUF/UD-IQ4_XS/Laguna-S-2.1-UD-IQ4_XS-00001-of-...gguf"),
    # so the repo folder isn't always the immediate parent -- walk up to the
    # first path segment that actually looks like a "<repo>-GGUF" directory,
    # falling back to the immediate parent if none is found.
    dir_parts = dirname.split(os.sep)
    repo = next((p for p in dir_parts if GGUF_REPO_SUFFIX_RE.search(p)), dir_parts[-1] if dir_parts else dirname)

    repo_clean = GGUF_REPO_SUFFIX_RE.sub("", repo).strip("-_ ") or repo

    quant_tag = group_stem
    if group_stem.lower().startswith(repo_clean.lower()):
        quant_tag = group_stem[len(repo_clean):].lstrip("-_ ")
    quant_tag = quant_tag or None

    return {
        "repo": repo_clean,
        "quant_tag": quant_tag,
        "group_key": (dirname, group_stem),
        "shard_num": shard_num,
        "shard_total": shard_total,
    }


def score_meta(entry):
    # How much real header data an entry carries -- used to pick which shard
    # of a multi-part GGUF to pull architecture/context/etc. from, since only
    # the first shard usually has a populated header.
    return sum(1 for k, v in entry.items() if k not in ("size_bytes", "size_human", "path") and v not in (None, False))


def load_models(catalog_path):
    with open(catalog_path) as f:
        raw = json.load(f)

    models = []
    models.extend(load_gguf_models(raw.get("gguf", {})))
    for rel_path, entry in raw.get("safetensors", {}).items():
        models.append(build_safetensors_row(rel_path, entry))
    return models


def load_gguf_models(gguf_catalog):
    groups = {}
    for rel_path, entry in gguf_catalog.items():
        if entry.get("is_vision_projector"):
            continue  # mmproj files are sidecars, not standalone models
        parsed = parse_gguf_filename(rel_path)
        groups.setdefault(parsed["group_key"], []).append((rel_path, entry, parsed))

    rows = []
    for group_key, parts in groups.items():
        best_rel, best_entry, best_parsed = max(parts, key=lambda p: score_meta(p[1]))
        total_bytes = sum(e.get("size_bytes", 0) for _, e, _ in parts)
        rows.append(build_gguf_row(best_rel, best_entry, best_parsed, parts, total_bytes))
    return rows


def friendly_gguf_name(parsed):
    if parsed["quant_tag"]:
        return f"{parsed['repo']} ({parsed['quant_tag']})"
    return parsed["repo"]


def build_gguf_row(rel_path, entry, parsed, parts, total_bytes):
    vision = bool(entry.get("is_vision_projector"))
    tools = bool(entry.get("chat_template_mentions_tool_calls"))
    shard_paths = sorted(p[0] for p in parts)
    return {
        "rel_path": parsed["group_key"][0] + "/" + parsed["group_key"][1] + ("*" if len(parts) > 1 else ""),
        "name": friendly_gguf_name(parsed),
        "format": "GGUF",
        "size_bytes": total_bytes,
        "size_human": human_size(total_bytes),
        "context_length": entry.get("context_length"),
        "vision": vision,
        "tools": tools,
        "architecture": entry.get("architecture"),
        "quant": f"file_type={entry.get('file_type')}",
        "shard_count": len(parts),
        "shard_paths": shard_paths,
        "raw": entry,
    }


def build_safetensors_row(rel_path, entry):
    name = os.path.basename(rel_path)  # e.g. "org/Phi-4" -> "Phi-4"
    vision = bool(entry.get("vision_config_present"))
    tools = bool(entry.get("chat_template_mentions_tool_calls"))
    return {
        "rel_path": rel_path,
        "name": name,
        "format": "safetensors",
        "size_bytes": entry.get("size_bytes", 0),
        "size_human": entry.get("size_human", human_size(entry.get("size_bytes", 0))),
        "context_length": entry.get("context_length"),
        "vision": vision,
        "tools": tools,
        "architecture": entry.get("architecture"),
        "quant": entry.get("quantization_config"),
        "shard_count": 1,
        "shard_paths": [rel_path],
        "raw": entry,
    }


SORTS = [
    ("size desc", lambda m: -m["size_bytes"]),
    ("size asc", lambda m: m["size_bytes"]),
    ("name", lambda m: m["name"].lower()),
    ("format", lambda m: (m["format"], m["name"].lower())),
]


def flag_str(m):
    v = "V" if m["vision"] else "-"
    t = "T" if m["tools"] else "-"
    return v + t


def safe_addnstr(stdscr, y, x, text, n, attr=0):
    # Writing into the terminal's bottom-right cell makes ncurses advance the
    # cursor past the window and raise ERR, even though the write itself
    # succeeded -- harmless, so just swallow it.
    try:
        stdscr.addnstr(y, x, text, n, attr)
    except curses.error:
        pass


def draw_list(stdscr, models, sel, scroll, total_bytes, sort_idx, filter_str):
    h, w = stdscr.getmaxyx()
    stdscr.erase()

    title = f" Model Manager -- {len(models)} models, {human_size(total_bytes)} total "
    safe_addnstr(stdscr, 0, 0, title.ljust(w), w, curses.A_REVERSE)

    sort_name = SORTS[sort_idx][0]
    subtitle = f" sort: {sort_name}  (s: cycle, /: filter, enter: details, q: quit)"
    if filter_str:
        subtitle += f"  filter: '{filter_str}'"
    safe_addnstr(stdscr, 1, 0, subtitle.ljust(w), w, curses.A_DIM)

    header = f"{'NAME':44} {'FMT':11} {'SIZE':>9} {'CTX':>9} {'VT':3} {'PTS':>3} ARCH"
    safe_addnstr(stdscr, 2, 0, header.ljust(w), w, curses.A_BOLD)

    list_top = 3
    visible_rows = h - list_top - 1
    if visible_rows < 1:
        visible_rows = 1

    for i in range(visible_rows):
        idx = scroll + i
        if idx >= len(models):
            break
        m = models[idx]
        ctx = f"{m['context_length']:,}" if m["context_length"] else "-"
        parts = str(m["shard_count"]) if m["shard_count"] > 1 else "-"
        line = (
            f"{m['name'][:44]:44} {m['format']:11} {m['size_human']:>9} "
            f"{ctx:>9} {flag_str(m):3} {parts:>3} {(m['architecture'] or '-')[:20]}"
        )
        attr = curses.A_REVERSE if idx == sel else curses.A_NORMAL
        safe_addnstr(stdscr, list_top + i, 0, line.ljust(w), w, attr)

    footer = " V=vision  T=tool-calling template  PTS=shard files merged  "
    if h - 1 > list_top:
        safe_addnstr(stdscr, h - 1, 0, footer.ljust(w), w, curses.A_DIM)

    stdscr.refresh()


def draw_detail(stdscr, m):
    h, w = stdscr.getmaxyx()
    stdscr.erase()

    title = f" {m['name']}  ({m['format']}) "
    safe_addnstr(stdscr, 0, 0, title.ljust(w), w, curses.A_REVERSE)
    safe_addnstr(stdscr, 1, 0, " esc/h/q: back ".ljust(w), w, curses.A_DIM)

    row = 3
    fields = [
        ("Path", m["rel_path"]),
        ("Disk usage", m["size_human"] + f"  ({m['size_bytes']:,} bytes)"),
        ("Shards", f"{m['shard_count']} file(s)" if m["shard_count"] > 1 else None),
        ("Architecture", m["architecture"]),
        ("Context length", f"{m['context_length']:,}" if m["context_length"] else None),
        ("Vision capable", "yes" if m["vision"] else "no"),
        ("Tool-calling template", "yes" if m["tools"] else "no"),
        ("Quant / dtype", m["quant"]),
    ]
    for label, value in fields:
        if value is None:
            continue
        safe_addnstr(stdscr, row, 2, f"{label:24} {value}", w - 2)
        row += 1

    if m["shard_count"] > 1:
        row += 1
        safe_addnstr(stdscr, row, 2, "Shard files:", w - 2, curses.A_BOLD)
        row += 1
        for p in m["shard_paths"]:
            if row >= h - 1:
                break
            safe_addnstr(stdscr, row, 4, os.path.basename(p), w - 4)
            row += 1

    row += 1
    safe_addnstr(stdscr, row, 2, "Raw catalog entry:", w - 2, curses.A_BOLD)
    row += 1
    raw_json = json.dumps(m["raw"], indent=2)
    for line in raw_json.splitlines():
        if row >= h - 1:
            safe_addnstr(stdscr, row, 2, "... (truncated)", w - 2, curses.A_DIM)
            break
        safe_addnstr(stdscr, row, 4, line, w - 4)
        row += 1

    stdscr.refresh()


def run(stdscr, catalog_path):
    curses.curs_set(0)
    all_models = load_models(catalog_path)
    total_bytes = sum(m["size_bytes"] for m in all_models)

    sort_idx = 0
    filter_str = ""
    sel = 0
    scroll = 0
    mode = "list"  # or "detail"

    def visible_models():
        models = all_models
        if filter_str:
            fl = filter_str.lower()
            models = [m for m in models if fl in m["name"].lower() or fl in m["rel_path"].lower()]
        return sorted(models, key=SORTS[sort_idx][1])

    while True:
        models = visible_models()
        sel = max(0, min(sel, len(models) - 1)) if models else 0

        if mode == "list":
            h, _ = stdscr.getmaxyx()
            visible_rows = max(1, h - 4)
            if sel < scroll:
                scroll = sel
            elif sel >= scroll + visible_rows:
                scroll = sel - visible_rows + 1
            draw_list(stdscr, models, sel, scroll, total_bytes, sort_idx, filter_str)
        else:
            draw_detail(stdscr, models[sel])

        key = stdscr.getch()

        if mode == "detail":
            if key in (27, ord("q"), ord("h"), curses.KEY_LEFT):
                mode = "list"
            continue

        # list mode
        if key in (ord("q"), 27):
            break
        elif key in (curses.KEY_UP, ord("k")):
            sel -= 1
        elif key in (curses.KEY_DOWN, ord("j")):
            sel += 1
        elif key in (curses.KEY_ENTER, 10, 13, ord("l"), curses.KEY_RIGHT):
            if models:
                mode = "detail"
        elif key == ord("s"):
            sort_idx = (sort_idx + 1) % len(SORTS)
        elif key == ord("/"):
            curses.echo()
            curses.curs_set(1)
            h, w = stdscr.getmaxyx()
            safe_addnstr(stdscr, h - 1, 0, "filter: ".ljust(w), w, curses.A_REVERSE)
            stdscr.move(h - 1, 8)
            entered = stdscr.getstr(h - 1, 8, 40).decode("utf-8", errors="ignore")
            curses.noecho()
            curses.curs_set(0)
            filter_str = entered
            sel = 0
            scroll = 0


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--catalog", default=DEFAULT_CATALOG)
    args = parser.parse_args()

    if not os.path.exists(args.catalog):
        raise SystemExit(
            f"Catalog not found at {args.catalog}. Run scripts/build_model_catalog.py first."
        )

    curses.wrapper(run, args.catalog)


if __name__ == "__main__":
    main()
